'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Pemex
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://ws.siic.portal/", ConfigurationName:="Pemex.ServicioPedidosClienteDelegate")>  _
    Public Interface ServicioPedidosClienteDelegate
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento arg0 del espacio de nombres  no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function enviaPedidosCliente(ByVal request As Pemex.enviaPedidosClienteRequest) As Pemex.enviaPedidosClienteResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="", ReplyAction:="*")>  _
        Function enviaPedidosClienteAsync(ByVal request As Pemex.enviaPedidosClienteRequest) As System.Threading.Tasks.Task(Of Pemex.enviaPedidosClienteResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class enviaPedidosClienteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="enviaPedidosCliente", [Namespace]:="http://ws.siic.portal/", Order:=0)>  _
        Public Body As Pemex.enviaPedidosClienteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Pemex.enviaPedidosClienteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class enviaPedidosClienteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public arg0 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public arg1 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public arg2 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public arg3() As Byte
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public arg4 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public arg5 As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal arg0 As String, ByVal arg1 As String, ByVal arg2 As String, ByVal arg3() As Byte, ByVal arg4 As String, ByVal arg5 As String)
            MyBase.New
            Me.arg0 = arg0
            Me.arg1 = arg1
            Me.arg2 = arg2
            Me.arg3 = arg3
            Me.arg4 = arg4
            Me.arg5 = arg5
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class enviaPedidosClienteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="enviaPedidosClienteResponse", [Namespace]:="http://ws.siic.portal/", Order:=0)>  _
        Public Body As Pemex.enviaPedidosClienteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Pemex.enviaPedidosClienteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="")>  _
    Partial Public Class enviaPedidosClienteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public [return]() As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal [return]() As Byte)
            MyBase.New
            Me.[return] = [return]
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServicioPedidosClienteDelegateChannel
        Inherits Pemex.ServicioPedidosClienteDelegate, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServicioPedidosClienteDelegateClient
        Inherits System.ServiceModel.ClientBase(Of Pemex.ServicioPedidosClienteDelegate)
        Implements Pemex.ServicioPedidosClienteDelegate
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Pemex_ServicioPedidosClienteDelegate_enviaPedidosCliente(ByVal request As Pemex.enviaPedidosClienteRequest) As Pemex.enviaPedidosClienteResponse Implements Pemex.ServicioPedidosClienteDelegate.enviaPedidosCliente
            Return MyBase.Channel.enviaPedidosCliente(request)
        End Function
        
        Public Function enviaPedidosCliente(ByVal arg0 As String, ByVal arg1 As String, ByVal arg2 As String, ByVal arg3() As Byte, ByVal arg4 As String, ByVal arg5 As String) As Byte()
            Dim inValue As Pemex.enviaPedidosClienteRequest = New Pemex.enviaPedidosClienteRequest()
            inValue.Body = New Pemex.enviaPedidosClienteRequestBody()
            inValue.Body.arg0 = arg0
            inValue.Body.arg1 = arg1
            inValue.Body.arg2 = arg2
            inValue.Body.arg3 = arg3
            inValue.Body.arg4 = arg4
            inValue.Body.arg5 = arg5
            Dim retVal As Pemex.enviaPedidosClienteResponse = CType(Me,Pemex.ServicioPedidosClienteDelegate).enviaPedidosCliente(inValue)
            Return retVal.Body.[return]
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Pemex_ServicioPedidosClienteDelegate_enviaPedidosClienteAsync(ByVal request As Pemex.enviaPedidosClienteRequest) As System.Threading.Tasks.Task(Of Pemex.enviaPedidosClienteResponse) Implements Pemex.ServicioPedidosClienteDelegate.enviaPedidosClienteAsync
            Return MyBase.Channel.enviaPedidosClienteAsync(request)
        End Function
        
        Public Function enviaPedidosClienteAsync(ByVal arg0 As String, ByVal arg1 As String, ByVal arg2 As String, ByVal arg3() As Byte, ByVal arg4 As String, ByVal arg5 As String) As System.Threading.Tasks.Task(Of Pemex.enviaPedidosClienteResponse)
            Dim inValue As Pemex.enviaPedidosClienteRequest = New Pemex.enviaPedidosClienteRequest()
            inValue.Body = New Pemex.enviaPedidosClienteRequestBody()
            inValue.Body.arg0 = arg0
            inValue.Body.arg1 = arg1
            inValue.Body.arg2 = arg2
            inValue.Body.arg3 = arg3
            inValue.Body.arg4 = arg4
            inValue.Body.arg5 = arg5
            Return CType(Me,Pemex.ServicioPedidosClienteDelegate).enviaPedidosClienteAsync(inValue)
        End Function
    End Class
End Namespace
